name: Release
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: |
          go install github.com/akavel/rsrc@latest
          mkdir -p bin/core/py
          mkdir released

          cd service && make windows-amd64 && cd ..

          rsrc -arch amd64 -manifest soulx.manifest -ico icon/32.ico,icon/48.ico,icon/64.ico,icon/128.ico,icon/256.ico -o soulx.syso

          ((Get-Content -path constant/version.go -Raw) -replace 'unknown version',$(git describe --tags --always)) | Set-Content -Path constant/version.go
          ((Get-Content -path constant/version.go -Raw) -replace 'unknown time',$(Get-Date -Format 'yyyy-MM-dd')) | Set-Content -Path constant/version.go

          make windows-amd64

          cd bin/core
          curl https://www.python.org/ftp/python/3.9.11/python-3.9.11-embed-amd64.zip -o py39-embed-amd64.zip
          Expand-Archive -Path py39-embed-amd64.zip -DestinationPath py && cd py
          cp python39.zip ../
          cp python39.dll ../ && cd ..
          Remove-Item -Force py39-embed-amd64.zip
          Remove-Item -Force -Recurse py && cd ../..
          Rename-Item bin soulx && cd soulx
          Compress-Archive -Path . -DestinationPath ../released/SoulX_$(Get-Date -Format 'yyyyMMdd')_$(git describe --tags --always).zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: released/*
          draft: false
